{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stone",
    "module": "myplugin",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "myplugin-1.1.jar",
          "url": "myplugin-1.1.jar",
          "size": 8987,
          "sha512": "b9cad640db08973e887bf72cd83bbb297c2006bcccbdc98e1596a39267149322f6e6fb0fba4871a6941468e8b7db3a16fdc97730f5640de7417a83c7ddaf976c",
          "sha256": "285746c685b016cd770b6520083d2abeaec1f30dca17c24f34fe796a1bf94794",
          "sha1": "cdf2af620d2730298c0d3f7e2af83b26f30be78f",
          "md5": "a19672370e679df1d02d0632d3b9c24e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myplugin-1.1.jar",
          "url": "myplugin-1.1.jar",
          "size": 8987,
          "sha512": "b9cad640db08973e887bf72cd83bbb297c2006bcccbdc98e1596a39267149322f6e6fb0fba4871a6941468e8b7db3a16fdc97730f5640de7417a83c7ddaf976c",
          "sha256": "285746c685b016cd770b6520083d2abeaec1f30dca17c24f34fe796a1bf94794",
          "sha1": "cdf2af620d2730298c0d3f7e2af83b26f30be78f",
          "md5": "a19672370e679df1d02d0632d3b9c24e"
        }
      ]
    }
  ]
}
