{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stone",
    "module": "myplugin",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "myplugin-1.1.jar",
          "url": "myplugin-1.1.jar",
          "size": 10310,
          "sha512": "302a3e18b529b65b37e9df352cb741cdc6799fef2c3f98588dc50dcd2b0344b6208ae8655fcd59a46f7200fe66087be901b792fb83ce8060b9d9d977d07853c4",
          "sha256": "675a5bad52df616bece575d4ad322d5eb3887b5a5559ba7be83249822eb5cc47",
          "sha1": "2e9eccd4ef90610c8adbdb4adea452926ba4fe25",
          "md5": "0de5634c6f54ec85d5eabf30a1527c55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myplugin-1.1.jar",
          "url": "myplugin-1.1.jar",
          "size": 10310,
          "sha512": "302a3e18b529b65b37e9df352cb741cdc6799fef2c3f98588dc50dcd2b0344b6208ae8655fcd59a46f7200fe66087be901b792fb83ce8060b9d9d977d07853c4",
          "sha256": "675a5bad52df616bece575d4ad322d5eb3887b5a5559ba7be83249822eb5cc47",
          "sha1": "2e9eccd4ef90610c8adbdb4adea452926ba4fe25",
          "md5": "0de5634c6f54ec85d5eabf30a1527c55"
        }
      ]
    }
  ]
}
